# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          # Version of pnpm to install
          version: 8.5.1
          # If specified, run `pnpm install`
          run_install: true

  publish-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: 'release.zip'
          exclusions: '*.git* *.github* *.vscode* /*node_modules/* /*src/* *.log .gitignore'
          # Tool to use for archiving
          type: zip
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.zip
